### ISSUE TITLE
FAVICON NOT TRANSPARENT

### ISSUE THREAD

**Issue by adilsaju** [adilsaju/yoke#100]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/22331455/202353887-b9d0f632-c62f-425d-bcb1-29bd18c98a85.png">

**Comment by clairesm** [comment]
COMPLETED.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/103476551/203179963-70e86264-eeff-4c33-8c92-51bb1884c3bb.png">
