### ISSUE TITLE
license issue in student dashboard

### ISSUE THREAD

**Issue by ritvikverma20** [adilsaju/yoke#123]
here in the student dashboard, there are only 3 licenses in a row. But it should be 4.

<img width="1026" alt="Screenshot 2022-11-19 at 2 50 29 PM" src="https://user-images.githubusercontent.com/111015993/202874588-3fa93655-eb74-453d-9232-35c996f7863d.png">

**Comment by clairesm** [comment]
Resolved in https://github.com/adilsaju/yoke/pull/191
