### ISSUE TITLE
(Web) Login page scrolling

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#130]
![image](https://user-images.githubusercontent.com/117692209/203170639-ed3c35c7-03a1-49f1-b708-2a060c81e8fa.png)
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
The login page image seems to be higher than the maximum height from my computer (1920 x 1080) (minus the windows bar and browser top bar), so the page is scrollable.

**Comment by Kirito9988** [comment]
To be done after final presentation(Only windows problem
