### ISSUE TITLE
(Web) Scan icon

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#135]
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
Typed credentials for student: mohitwadhwa1233@gmail.com and its password.
Double clicked "login" button.
Clicked "update" button at the top right corner of "updates".
Clicked "Scan" button under Pilot License.
BUG: It still has the camera icon.
![image](https://user-images.githubusercontent.com/117692209/203172559-6fbdf353-bc35-47cd-a760-963f6505d5c2.png)

**Comment by clairesm** [comment]
Resolved here:
https://github.com/adilsaju/yoke/pull/181
