### ISSUE TITLE
(Web) Tab Navigation Upload license pt.2

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#140]
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
Typed credentials for student: [mohitwadhwa1233@gmail.com](mailto:mohitwadhwa1233@gmail.com) and its password.
Double clicked "login" button.
Clicked "update" button at the top right corner of "updates".
Clicked "Scan" button under Pilot License.
Received confirmation after clicking the photo.
Clicked "upload" button under Pilot License.
Got confirmation after uploading an image from the computer.
Tried tab navigation. After going through every navigation bar item, the selection does not go through the "update" and "scan" options, it goes directly to "cancel". It also appeared a ghost option in between "cancel" button and "save" button, which takes the user back to the student profile without any confirmation or the changes made.

![image](https://user-images.githubusercontent.com/117692209/203173953-415f9512-f4c3-4521-8a89-ea49f5ea44bd.png)
![image](https://user-images.githubusercontent.com/117692209/203173971-657ede2b-8a8e-4ecb-af45-1a4cc13a55a1.png)
![image](https://user-images.githubusercontent.com/117692209/203174863-6b6fac5f-555d-41e1-b71e-5134b1e875fb.png)
![image](https://user-images.githubusercontent.com/117692209/203174734-ca669f06-4d56-4c5f-8d4e-118bdd6c2f95.png)

**Comment by mohitgit1233** [comment]
This is a very common user flow, when you navigate to another page, the changes go away. That is why we have a save button in the first place. Even here in github if you write a comment and go back to issues page, the comment disappears.
