### ISSUE TITLE
(Web) Empty license after uploading

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#142]
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
Typed credentials for student: [mohitwadhwa1233@gmail.com](mailto:mohitwadhwa1233@gmail.com) and its password.
Double clicked "login" button.
Clicked "update" button at the top right corner of "updates".
Clicked "Scan" button under Pilot License.
Received confirmation after clicking the photo.
Clicked "upload" button under Pilot License.
Got confirmation after uploading an image from the computer.
After clicking "Save" button, got confirmation, but image area displayed empty prompts for a while after action.
![image](https://user-images.githubusercontent.com/117692209/203175015-fca4b9cc-f290-45e5-9c20-24ef900b1073.png)

**Comment by Kirito9988** [comment]
This happens because its saving in the backend that's why it reloads
