### ISSUE TITLE
(Web) Student Account Page scrollable horizontally.

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#144]
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
Typed credentials for student: [mohitwadhwa1233@gmail.com](mailto:mohitwadhwa1233@gmail.com) and its password.
Double clicked "login" button.
Clicked "update" button at the top right corner of "updates".
Clicked "Scan" button under Pilot License.
Received confirmation after clicking the photo.
Clicked "upload" button under Pilot License.
Got confirmation after uploading an image from the computer.
After clicking "Save" button, got confirmation, but image area displayed empty prompts for a while after action. Then images show again.
Clicked "Account Details" and returned to student profile page. The page turned to scrollable to the left and right, which is not what it should be doing.
![image](https://user-images.githubusercontent.com/117692209/203175601-af761225-c647-4d7f-bd4e-70359bcd7536.png)

**Comment by Kirito9988** [comment]
To be done after final presentation.(Only windows problem)
