### ISSUE TITLE
(Web)

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#148]
After typing yokeaviation.ca on my browser bar, I'm directed to the login page.
Typed credentials for student: [mohitwadhwa1233@gmail.com](mailto:mohitwadhwa1233@gmail.com) and its password.
Double clicked "login" button.
Clicked "update" button at the top right corner of "updates".
Clicked "Scan" button under Pilot License.
Received confirmation after clicking the photo.
Clicked "upload" button under Pilot License.
Got confirmation after uploading an image from the computer.
After clicking "Save" button, got confirmation, but image area displayed empty prompts for a while after action. Then images show again.
Clicked "Account Status" and returned to student profile page. The page turned to scrollable to the left and right, which is not what it should be doing.
Clicked "Student Travel Order" , tried dynamic search bar - working. Table filtered according to typed element.
Clicked "request travel order" button, 
Opened calendar for date deciding. Clicked on "25" under November. Received confirmation pop-up "Booking Submitted for November 25th , 2022"
Clicked "ok", sent ti tlist of requested travel orders.
Application is thee.

**Comment by Kirito9988** [comment]
To be done after final presentation
