### ISSUE TITLE
Ok is not correct for confirming and its in red color. Please change this Ok to some green color icon. Take icon from UI Components in Figma

### ISSUE THREAD

**Issue by jvrajpoot** [adilsaju/yoke#149]
![image](https://user-images.githubusercontent.com/117692184/203176638-7ef3e2c3-5860-48ed-a653-f814f2657539.png)
![image](https://user-images.githubusercontent.com/117692184/203176716-60bbc2a8-a2b1-4b40-8f95-003236de8358.png)

**Comment by adilsaju** [comment]
duplicate
