### ISSUE TITLE
404 page api NOT WORKING (errorMiddleware.js)

### ISSUE THREAD

**Issue by adilsaju** [adilsaju/yoke#15]
1. Run backend
2. go to any route other than specified
3. Should display error not found page

**Comment by adilsaju** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [404 page api NOT WORKING (errorMiddleware.js)](https://trello.com/c/Kz3tVU9n/17-404-page-api-not-working-errormiddlewarejs)

**Comment by clairesm** [comment]
https://github.com/adilsaju/yoke/pull/17
