### ISSUE TITLE
Padding and Margin should be matched with mockups

### ISSUE THREAD

**Issue by jvrajpoot** [adilsaju/yoke#150]
![image](https://user-images.githubusercontent.com/117692184/203176856-bd87514a-6439-4b21-8a6d-cb5d472196c1.png)
![image](https://user-images.githubusercontent.com/117692184/203176905-b0c81c97-4d24-4a35-af01-16b0bb23c0df.png)

**Comment by mohitgit1233** [comment]
<img width="596" alt="Screenshot 2022-11-28 at 4 35 51 AM" src="https://user-images.githubusercontent.com/107973422/204279269-25dbead3-2445-4423-bf0d-8e1059858c46.png">

**Comment by mohitgit1233** [comment]
This is how it looks when matched with mockups, so we cannot do exactly like mockup, just tell if the padding is less .
