### ISSUE TITLE
(Web) Dashboard screen horizontally scrolling

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#156]
After clicking "Log Out" from student side. I'm redirected to the login page.
Entered administrator credentials: claire@yoke.com and its password.
Clicked on "show password" icon, password showed.
Clicked on "hide password" icon, password hidden.
Tabbed from email input, went to password input, to hide/password,  to forgot password?, to login.
Pressed enter, redirected to "dashboard."
Dashboard horizontally scrollable for my 1920x1080 screen size (minus left bar from browser).
![image](https://user-images.githubusercontent.com/117692209/203180462-a1255c1a-71c8-4acc-b0a8-4381d9478c30.png)

**Comment by Kirito9988** [comment]
To be done after final presentation
