### ISSUE TITLE
(Web) Mouse shows unusual state over "Dashboard" page header.

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#157]
After clicking "Log Out" from student side. I'm redirected to the login page.
Entered administrator credentials: claire@yoke.com and its password.
Clicked on "show password" icon, password showed.
Clicked on "hide password" icon, password hidden.
Tabbed from email input, went to password input, to hide/password,  to forgot password?, to login.
Pressed enter, redirected to "dashboard."

BUG: Mouse shows unusual state over "Dashboard" page header.

![image](https://user-images.githubusercontent.com/117692209/203180742-029a371e-e9bd-4158-9b48-507fa19922ae.png)

**Comment by Kirito9988** [comment]
That is intended
