### ISSUE TITLE
(Web) Tab Navigation - admin side

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#160]
After clicking "Log Out" from student side. I'm redirected to the login page.
Entered administrator credentials: [claire@yoke.com](mailto:claire@yoke.com) and its password.
Clicked on "show password" icon, password showed.
Clicked on "hide password" icon, password hidden.
Tabbed from email input, went to password input, to hide/password, to forgot password?, to login.
Pressed enter, redirected to "dashboard."
Pressed TAB, first started through side nav bar options: Dashboard, Travel Order, Travel order number .

BUG: Recognizes number of travel orders pending and final list students as individual elements
![image](https://user-images.githubusercontent.com/117692209/203181201-4b899ceb-548c-4f66-be05-4a4d5f18b01d.png)
![image](https://user-images.githubusercontent.com/117692209/203181964-90b0fc61-a1b2-4967-af8c-2efb5bd48730.png)

**Comment by Kirito9988** [comment]
It should does it
