### ISSUE TITLE
(Web) - Wrong (Temporary) information

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#164]
Clicked on Travel Order menu option.
Search bar working.
Sort working.
Tab order working.
Clicked ENTER, accessed student profile.

BUG - When going through one request to another using the top right corner arrows., shows wrong (temporary) information.
![image](https://user-images.githubusercontent.com/117692209/203182851-6a8f3f10-1b30-4617-b11a-da2b6ba6f70e.png)

**Comment by Kirito9988** [comment]
To be done after final presentation
