### ISSUE TITLE
(Web) - Note note saved.

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#166]
Before declining Mohit's license, note had been edited and added the phrase "All This Heaven". but after declining and trying to click undo, note was not shown as updated.

![image](https://user-images.githubusercontent.com/117692209/203183841-c00dd80e-4d35-45b0-a0a5-e19a5914b3ad.png)

**Comment by Kirito9988** [comment]
Not able to reproduce this and works fine for me so resolved from my side and closing this with comment
