### ISSUE TITLE
(Web) - Reset password from Setting Lacks styling

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#168]
![image](https://user-images.githubusercontent.com/117692209/203184915-bafef840-503d-42fb-b125-88b4ef01e496.png)

**Comment by mohitgit1233** [comment]
<img width="550" alt="Screenshot 2022-11-28 at 12 42 54 AM" src="https://user-images.githubusercontent.com/107973422/204232543-ce9a7aa9-73ff-4c92-b0bf-ca42ca2e8d69.png">

Done with minor changes
