### ISSUE TITLE
(Mobile) - Final List not updating

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#172]
After approving three (3) travel order requests through Claire credentials, the final list did not update.
Phone: iPhone 14 mini, browser safari.

![image](https://user-images.githubusercontent.com/117692209/203186364-66ad25be-b91f-41af-afaa-ef85f88e286a.png)

![image](https://user-images.githubusercontent.com/117692209/203186342-3bc93303-1a2c-4dbe-9f05-633c7a5147ec.png)

**Comment by Kirito9988** [comment]
I cant reproduce this and this works fine on the server and for me so closing this issue
