### ISSUE TITLE
Mobile: Logo not aligned

### ISSUE THREAD

**Issue by clairesm** [adilsaju/yoke#189]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/103476551/203487886-aa9e1c7f-d5a2-4310-ae11-076a25e4e989.png">

**Comment by misserism** [comment]
Resolved in https://github.com/adilsaju/yoke/pull/188

**Comment by clairesm** [comment]
Resolved in https://github.com/adilsaju/yoke/pull/188
