### ISSUE TITLE
View Profile page clicked from Final List is BUGGY

### ISSUE THREAD

**Issue by adilsaju** [adilsaju/yoke#24]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/22331455/199521103-d61148e1-69a5-4e11-9017-2921e10634f1.png">

- View Profile page is compeltely perfect when clicked from travel order page list
- Some profiles (eg. Bhanuj's), showing -1 index out range
- -1 because the checking list is different compared to /pendingRequests

**Comment by Kirito9988** [comment]
Working on it

**Comment by Kirito9988** [comment]
Done
