### ISSUE TITLE
BACKEND: Route /students/:id getRequestsByStudentId() return bug

### ISSUE THREAD

**Issue by adilsaju** [adilsaju/yoke#3]
if req.query.student is empty, its returning all data fix that
steps to repr:

- go to postman
- run the same api with empty query parameters
- check the response. It should return error instead of giving all data

**Comment by clairesm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BACKEND: Route /students/:id getRequestsByStudentId() return bug](https://trello.com/c/YroVRj3X/7-backend-route-students-id-getrequestsbystudentid-return-bug)
