### ISSUE TITLE
Backend Firebase upload failing

### ISSUE THREAD

**Issue by adilsaju** [adilsaju/yoke#4]

**Comment by clairesm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backend Firebase upload failing #4](https://trello.com/c/VNvpER7w/6-backend-firebase-upload-failing-4)

**Comment by clairesm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BACKEND: Route /students/:id getRequestsByStudentId() return bug](https://trello.com/c/YroVRj3X/7-backend-route-students-id-getrequestsbystudentid-return-bug)

**Comment by adilsaju** [comment]
DONE
