### ISSUE TITLE
BUG BASH: Login screen

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#41]
When first accessing log in page, image is larger than it should, no margin from top or bottom. 
E-mail input smaller size than password. Incorrect icon usage for show hide password.
Bigger button size, not started with caps.

Assigned to: @adilsaju

**Comment by cpg00** [comment]
Password input when focused excludes eye icon

**Comment by cpg00** [comment]
not completed navigatabled by keyboard, enter does not trigger login.

**Comment by adilsaju** [comment]
ENTER KEY FIXED
