### ISSUE TITLE
bug bash : dashboard page (admin user)

### ISSUE THREAD

**Issue by ritvikverma20** [adilsaju/yoke#43]
After login on the dashboard page

<img width="465" alt="Screenshot 2022-11-07 at 3 10 43 PM" src="https://user-images.githubusercontent.com/111015993/200437045-7a12d801-5b11-4c25-ab85-68f1448bd5c4.png">

**Comment by adilsaju** [comment]
Please don't report bug from dev console😂. Focus on stuff happening in ui for end user.

**Comment by adilsaju** [comment]
And try to add steps to reproduce

**Comment by adilsaju** [comment]
closing now
