### ISSUE TITLE
Bug bash: side bar for the dashboard

### ISSUE THREAD

**Issue by ritvikverma20** [adilsaju/yoke#44]
When the user reloads the page the unread travel order and final list data show 0 instead of real numbers. It takes time but after 2-3s it changes the data.
<img width="294" alt="Screenshot 2022-11-07 at 3 13 26 PM" src="https://user-images.githubusercontent.com/111015993/200437188-41885539-331a-414f-9843-d41325b94870.png">

**Comment by adilsaju** [comment]
Working on it
