### ISSUE TITLE
Bug bash: login credentials still there in the input fields

### ISSUE THREAD

**Issue by ritvikverma20** [adilsaju/yoke#47]
After logging out from the account and when I re-login the credentials remain in the input field. It supposes to be clear after reloading.
<img width="504" alt="Screenshot 2022-11-07 at 3 32 08 PM" src="https://user-images.githubusercontent.com/111015993/200437754-1ccb2718-170b-4868-9908-20bfa3f8012d.png">

**Comment by adilsaju** [comment]
Maybe its google chrome cache

**Comment by adilsaju** [comment]
closing now (bcoz of chrome saved pwd only)
