### ISSUE TITLE
Bug Bash - Profile opens without login with only just url

### ISSUE THREAD

**Issue by jvrajpoot** [adilsaju/yoke#51]
![image](https://user-images.githubusercontent.com/117692184/200438356-4c1f1b00-35e0-459b-9f37-6de9482aa1d3.png)

**Comment by adilsaju** [comment]
Same thing I commented on group

**Comment by jvrajpoot** [comment]
But still there is an issue, this issue I will show you in the meeting.

**Comment by adilsaju** [comment]
Tried in incognito, redirecting to login page properly. CLOSING!!!!
