### ISSUE TITLE
Bug bash: the data in the list should be sorted, student dashboard

### ISSUE THREAD

**Issue by ritvikverma20** [adilsaju/yoke#55]
The data in the student travel order is not sorted. The list should be shorted according to the date.

<img width="628" alt="Screenshot 2022-11-07 at 3 43 32 PM" src="https://user-images.githubusercontent.com/111015993/200438974-4b82f8e2-3da5-4c66-9bc0-2eaa9ac678d1.png">

**Comment by Kirito9988** [comment]
This is done already
