### ISSUE TITLE
BUG BASH: STUDENT(MOHIT) SETTINGS

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#57]
- there is no setting for students on mock up (are we adding as a new feature, agreeded by team?)
- Forgot password button does nothing (give message or something, it has to have functionality even if it is link to reset sent to email, do`nt let it just be decorative it`s going to surive to beta)

**Comment by adilsaju** [comment]
Already raised this as bug by Jasmeen

**Comment by adilsaju** [comment]
CLOSING
