### ISSUE TITLE
BUG BASH: ADMIN - travel order + NAV BAR

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#59]
When clciked on travel order, there is no actived version, it does not become different from the not activaed tabs.
  (NUMBERS ARE NAVIGTABLE THROUGH KEY BOARD, SHOULD NOT HAPPEN)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/117692209/200441531-d357a76c-0fe4-4cff-8ba5-e834147f99ad.png">
(<- BACK) AND (>) are being double navigatble by keyboard (tab).
EDIT button not clickable.
NOTE BOX is automatically editable by tab, should it be that way? Feels like it shouldn`t

WHEN there is only one studen request, instead of no request navigation (lack of (>) ), it shows a 0, it should not happen.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/117692209/200442377-04fb97c9-6606-496b-aa58-d59ff7001032.png">

WHEN Empty, there is no message to let admin know what to expect.

**Comment by adilsaju** [comment]
Do you have active state in the mockup??😨

**Comment by cpg00** [comment]
@adilsaju change word "activated" to when tab is selected

**Comment by clairesm** [comment]
Active state resolved. The pagination issue was also raised on other open issues.
