### ISSUE TITLE
Bug Bash: confirmation email

### ISSUE THREAD

**Issue by clairesm** [adilsaju/yoke#72]
It should be clarified that the student’s request has been approved (because they have complete and valid documents) and it will be forwarded to flight coordinator (and maybe wait for final flight schedule or wait for schedule confirmation from flight coordinator)

admins do not have access to the airport/hangar/plane schedule and can’t confirm.

this is to set the “student’s expectations”

**Comment by adilsaju** [comment]
@misserism add content please in emailcontroller

**Comment by clairesm** [comment]
COMPLETED
