### ISSUE TITLE
Bug Bash - Documents Sequences should be same on both screens

### ISSUE THREAD

**Issue by jvrajpoot** [adilsaju/yoke#79]
![image](https://user-images.githubusercontent.com/117692184/200481876-c5728196-0265-4e83-8725-72a717225288.png)
![image](https://user-images.githubusercontent.com/117692184/200481906-06e5c06b-0ce8-4a39-b469-6908c0921079.png)

**Comment by adilsaju** [comment]
Good observation 😅

**Comment by clairesm** [comment]
COMPLETED
