### ISSUE TITLE
BUG BASH MOBILE (ALL in one) - Not responsive

### ISSUE THREAD

**Issue by cpg00** [adilsaju/yoke#80]
![image](https://user-images.githubusercontent.com/117692209/200482820-ff469b45-7161-4b4c-908d-6309a8fdd791.png)
As soon as the user goes into the mobile version login in page, it is obvious that the site was not created with responsiveness in mind. The style is all broken. What is the word "plase" doing there?
Same thing happens to all other pages:
![image](https://user-images.githubusercontent.com/117692209/200483276-1f7ac217-4005-4b26-a5a5-a273da62c88e.png)
At te very least the documents are stacked:
![image](https://user-images.githubusercontent.com/117692209/200483492-5d29564b-763a-4e31-a4aa-d6ec679d30ba.png)

Please, focus on making it work for all devices as promised on landing page, before thinking of more features.

**Comment by adilsaju** [comment]
WE HAVEN'T EVEN STARTED MOBILE VIEW, YOU DON'T HAVE TO RAISE A BUG FOR THIS LOL

**Comment by cpg00** [comment]
Take it as a reminder then
