### ISSUE TITLE
Desktop: Total No. of Students - Number

### ISSUE THREAD

**Issue by clairesm** [adilsaju/yoke#98]
needs to be in the center

<img width="203" alt="image" src="https://user-images.githubusercontent.com/103476551/202348843-095f0fdb-0869-4eaa-b837-321142f30c10.png">

**Comment by misserism** [comment]
Resolved in https://github.com/adilsaju/yoke/pull/182

**Comment by clairesm** [comment]
Resolved in https://github.com/adilsaju/yoke/pull/182
